#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE $DB_ROLE_ADMIN WITH
        NOLOGIN
        NOSUPERUSER
        NOCREATEDB
        CREATEROLE
        BYPASSRLS
        NOINHERIT
        NOREPLICATION
        CONNECTION LIMIT -1;
    GRANT ALL ON SCHEMA public TO $DB_ROLE_ADMIN;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO $DB_ROLE_ADMIN;

    CREATE ROLE $DB_USER_GENERAL WITH
        LOGIN
        NOSUPERUSER
        NOINHERIT
        NOCREATEDB
        NOCREATEROLE
        NOREPLICATION
        CONNECTION LIMIT -1
        PASSWORD '$DB_USER_GENERAL_PASSWORD';
    GRANT $DB_ROLE_ADMIN TO $DB_USER_GENERAL;
EOSQL